### ISSUE TITLE
career support - resumes - Build your Resume

### ISSUE THREAD

**Issue by ktrammell95** [hjohnson120/assignments#21]
Key areas of Information to include:

## Contact information
- [x] Email
- [x] Phone Number (Google numbers are great if you want to protect your personal number)
- [x] Github link
- [x] Portfolio link

## Summary 
- [ ]  Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” simply use a headline that encapsulates your credentials.

## Skills 
- [x]  You’ll want to incorporate the right keywords so that your resume is optimized for application tracking systems

## Professional experience
- [x]  Focus on your accomplishments rather than your day-to-day responsibilities

## Education
- [x]  Simply write where you went college and your degree.
- [x]  It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ]  Volunteering and community service

## Due Date: Wednesday, June 19th
- [ ]  Upload or submit a link to your resume for review.

**Comment by hjohnson120** [comment]
[hjohnson-ledlie-resume.pdf](https://github.com/hjohnson120/assignments/files/3297290/hjohnson-ledlie-resume.pdf)

**Comment by ktrammell95** [comment]
Your format is beautiful, think about adding skills like Git, GitHub, Slack, Trello things that show the tech tools you are also familiar with.

Also, build out your SDG a bit under experience, you can give a few project examples or at least talk about React or .Net.  You want to show you have the dev skills as much as you can on your resume

**Comment by ktrammell95** [comment]
Your homework was marked: **Meets Expectations**

![Nice Execution](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--435c403e412f36135a8ed75de354d9a9b3fb4830/tenor.gif)
> &ldquo;Nice Execution&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/84)**__

**Comment by hjohnson120** [comment]
[6:19:19hjohnson_Ledlie.pdf](https://github.com/hjohnson120/assignments/files/3307451/6.19.19hjohnson_Ledlie.pdf)
