### ISSUE TITLE
week 06 - day 02  - choose your own adventure

### ISSUE THREAD

**Issue by mdewey** [hjohnson120/assignments#22]
# Choose your own API Adventure

In this assignment, you'll build a front end for an API of your choice

## Objectives

- Reinforce component architecture in React
- Reinforce reading of API documentation (some are great, and some are terrible)
- Creating and designing your own features for a web app

## Requirements

We're going to build a front end for an API of your choice. Choose one from [this list](https://github.com/toddmotto/public-apis) or an API that you are aware of. 

_NOTE_ You'll need to choose one with `Auth` being `No` or `apiKey` since we haven't covered `OAuth` authentication yet.

_NOTE_ You'll also need to check to see if the API will work from your browser. You can do a quick check by making a small `app-app`, doing an `axios.get` or `fetch` of one API URL and see if you get browser errors.

### Explorer Mode

- [x] Select an API and get it approved by your instructor.
- [x] Read your API docs
- [x] Use Postman to make some API requests to be familiar with the API and the data it returns
- [x] Create a list of the features you are going to create and how they will work
- [x] Design your User Interface
- [x] Design your HTML statically in `App.js`
- [x] Make it dynamic
- [x] Use components when needed
- [x] Deploy it and share it with friends

### Adventure Mode

- [ ] Add multiple pages to your site.
- [ ] Add a second API
- [ ] Work on components and clean, well-commented code.
- [ ] Work on other assignments you might be assigned as well. Career support or old adventure modes come to mind.
- [ ][do you wanna build a snowman?] (https://suncoast.io/handbook/curriculum/front-end/react-ii/assignments/snowman)

### Epic mode
- [ ] Capstones are going to be coming sooner rather than later. Check out [this resource](https://suncoast.io/handbook/curriculum/final-project/project-ideas/) To help get you started.

**Comment by hjohnson120** [comment]
https://github.com/hjohnson120/recipe-api

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Get up and dance!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBSdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3323b129c4533d8a45339c345692fab77f9771ac/meets-1.gif)
> &ldquo;Get up and dance!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/61)**__
