### ISSUE TITLE
Week 07 - day 02  - A Whole New World!

### ISSUE THREAD

**Issue by mdewey** [hjohnson120/assignments#27]
# A Whole New World

Today you learned a new language and will be starting to explore it more in depth in the coming weeks. Like any good craftsman, the first thing you need is to learn your tools. Tonight, you will be setting up your developer environment, creating a simple console application, and starting your final project.

## Objectives

- Set up your dev machines
- Create a simple console application to ensure your machine is set up correctly
- Write a blog article to practice talking about technology

### .NET Students

- Install the [.NET Core SDK](https://www.microsoft.com/net/download).
- Install the follow plugins:

  - [x] [`C#`](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp)
  - [x] [`C# extensions`](https://marketplace.visualstudio.com/items?itemName=jchannon.csharpextensions)
  - [x] [`C# code snippets`](https://marketplace.visualstudio.com/items?itemName=jorgeserrano.vscode-csharp-snippets)
  - [x] [ `.gitignore'](https://marketplace.visualstudio.com/items?itemName=hasanali.gitignore-templates)

- To verify everything was installed correctly, run `dotnet -v` in your terminal.

### Ruby

You should already have Ruby installed.

#### Simple Console Application

- [x] Create a console application that guesses a number that a user has thought of, between 1 and 100. This will use a [`binary search`](https://www.programmerinterview.com/index.php/puzzles/minimum-guesses-1-100/) to guess the correct number

- [x] Here is the JavaScript, browser-based, algorithm to follow. Make sure to understand this first before writing new code: [`https://codepen.io/ambethia/pen/KNewBb`](https://codepen.io/ambethia/pen/KNewBb).
      **NOTE** You will be translating this from the event-driven paradigm of HTML to the more procedural paradigm of a console application.
- [x] For Explorer Mode, you do not have to put in the menu or other user experience "nice to haves", focus on the just the core algorithm.

#### Wireframes and Ideas

- [ ] Work on your wireframes and ironing out your idea. Work with your instructors and peers to work out the kinks. Ideas should be approved by tomorrow.

### Adventure Mode

- [ ] Add nice user experience to the console app. Include features such as
      `Try again` and `Welcome, press enter to start`

### Epic Mode

- [ ] Eventually, we will be using an [MVC](https://dotnet.microsoft.com/apps/aspnet/mvc) application structure. To prepare for this, refactor your code to have all your business logic in a separate class and all your console interaction in the main class.

## Additional Resources

- .NET

  - [.NET Documentation](https://docs.microsoft.com/en-us/dotnet/)

**Comment by hjohnson120** [comment]
https://github.com/hjohnson120/a-whole-new-world

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bceeb145d881263a0f2f05f92594ddf64d6d8c0a/giphy-13.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/78)**__
