### ISSUE TITLE
week 02 - day 02  - scoreboard part ii

### ISSUE THREAD

**Issue by mdewey** [hjohnson120/assignments#6]
# Score Board, Part 2

For this assignment, you will extending and giving your scoreboard additional features.

## Requirements

- use last's nights project, add a max score, a min score, and a winner.

### Explorer Mode

- [x] Add a `if` statement to stop each team's score from going below 0.
- [x] Add an `if` statement to stop each team's score from going above 21
- [x] When a team gets 21 points, disable the buttons and display an message to the user of who won
- [x] Add a `reset` button that resets the scoreboard back to the each team having 0 points and re-enables the buttons. This button should not reset the page without having the page refreshed.

### Adventure Mode

- [ ] Add more CSS to the winning teams score to indicate who won.
- [ ] Implement a Quarter/Period Tracker that would be appropriate for the sport.
- [ ] Add some styling to make it more presentable. Have fun with it.
- [ ] Make the layout responsive.

### Epic Mode

- [ ] Add a Timer that counts down automatically and updates the period/quarter appropriately.
- [ ] Save/load the information to local storage.
- [ ] Add anything else that your sport would have on its scoreboard (e.g. fouls, sacks, shots on goal, etc.).
- [ ] Improve the UX to help to make scorekeeping by your sport easier.

### Super Epic mode

- [ ] Build the popular game "rock paper scissors"

**Comment by hjohnson120** [comment]
https://github.com/hjohnson120/scoreboard-ii.git

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6653a5b4c8e877384d759556a53bfc97521ca49f/giphy-17.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/82)**__
